project_id: '734021'
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /po/eye-on-cursor.pot
    translation: /po/%two_letters_code%.po
    type: gettext
    languages_mapping:
      two_letters_code:
        en-GB: en_GB
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW
